// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: dynamic_server_go/calculator.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArithmeticOpArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg1 int32 `protobuf:"varint,1,opt,name=arg1,proto3" json:"arg1,omitempty"`
	Arg2 int32 `protobuf:"varint,2,opt,name=arg2,proto3" json:"arg2,omitempty"`
}

func (x *ArithmeticOpArguments) Reset() {
	*x = ArithmeticOpArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_server_go_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArithmeticOpArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArithmeticOpArguments) ProtoMessage() {}

func (x *ArithmeticOpArguments) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_server_go_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArithmeticOpArguments.ProtoReflect.Descriptor instead.
func (*ArithmeticOpArguments) Descriptor() ([]byte, []int) {
	return file_dynamic_server_go_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *ArithmeticOpArguments) GetArg1() int32 {
	if x != nil {
		return x.Arg1
	}
	return 0
}

func (x *ArithmeticOpArguments) GetArg2() int32 {
	if x != nil {
		return x.Arg2
	}
	return 0
}

type SingleIntResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res int32 `protobuf:"varint,1,opt,name=res,proto3" json:"res,omitempty"`
}

func (x *SingleIntResult) Reset() {
	*x = SingleIntResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_server_go_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleIntResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleIntResult) ProtoMessage() {}

func (x *SingleIntResult) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_server_go_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleIntResult.ProtoReflect.Descriptor instead.
func (*SingleIntResult) Descriptor() ([]byte, []int) {
	return file_dynamic_server_go_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *SingleIntResult) GetRes() int32 {
	if x != nil {
		return x.Res
	}
	return 0
}

type ListArithmeticOpArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []int32 `protobuf:"varint,2,rep,packed,name=args,proto3" json:"args,omitempty"`
}

func (x *ListArithmeticOpArguments) Reset() {
	*x = ListArithmeticOpArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_server_go_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListArithmeticOpArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListArithmeticOpArguments) ProtoMessage() {}

func (x *ListArithmeticOpArguments) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_server_go_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListArithmeticOpArguments.ProtoReflect.Descriptor instead.
func (*ListArithmeticOpArguments) Descriptor() ([]byte, []int) {
	return file_dynamic_server_go_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *ListArithmeticOpArguments) GetArgs() []int32 {
	if x != nil {
		return x.Args
	}
	return nil
}

type Complex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Real float64 `protobuf:"fixed64,1,opt,name=real,proto3" json:"real,omitempty"`
	Imag float64 `protobuf:"fixed64,2,opt,name=imag,proto3" json:"imag,omitempty"`
}

func (x *Complex) Reset() {
	*x = Complex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_server_go_calculator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Complex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Complex) ProtoMessage() {}

func (x *Complex) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_server_go_calculator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Complex.ProtoReflect.Descriptor instead.
func (*Complex) Descriptor() ([]byte, []int) {
	return file_dynamic_server_go_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *Complex) GetReal() float64 {
	if x != nil {
		return x.Real
	}
	return 0
}

func (x *Complex) GetImag() float64 {
	if x != nil {
		return x.Imag
	}
	return 0
}

type ListComplexOpArguments struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Args []*Complex `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *ListComplexOpArguments) Reset() {
	*x = ListComplexOpArguments{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamic_server_go_calculator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListComplexOpArguments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListComplexOpArguments) ProtoMessage() {}

func (x *ListComplexOpArguments) ProtoReflect() protoreflect.Message {
	mi := &file_dynamic_server_go_calculator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListComplexOpArguments.ProtoReflect.Descriptor instead.
func (*ListComplexOpArguments) Descriptor() ([]byte, []int) {
	return file_dynamic_server_go_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *ListComplexOpArguments) GetArgs() []*Complex {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_dynamic_server_go_calculator_proto protoreflect.FileDescriptor

var file_dynamic_server_go_calculator_proto_rawDesc = []byte{
	0x0a, 0x22, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x69, 0x63, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x5f, 0x67, 0x6f, 0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x22, 0x3f, 0x0a, 0x15, 0x41, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f, 0x70,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x31, 0x12, 0x12, 0x0a,
	0x04, 0x61, 0x72, 0x67, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x61, 0x72, 0x67,
	0x32, 0x22, 0x23, 0x0a, 0x0f, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x2f, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f, 0x70, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x05, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x22, 0x31, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x70, 0x6c,
	0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x72, 0x65, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6d, 0x61, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x69, 0x6d, 0x61, 0x67, 0x22, 0x41, 0x0a, 0x16, 0x4c, 0x69,
	0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4f, 0x70, 0x41, 0x72, 0x67, 0x75, 0x6d,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x32, 0xa9, 0x01,
	0x0a, 0x0a, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x4a, 0x0a, 0x06,
	0x41, 0x64, 0x64, 0x54, 0x77, 0x6f, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f, 0x70,
	0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0b, 0x53, 0x75, 0x62, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x54, 0x77, 0x6f, 0x12, 0x21, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f,
	0x70, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e,
	0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x32, 0x83, 0x02, 0x0a, 0x12, 0x41, 0x64,
	0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x4f, 0x0a, 0x0b, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x79, 0x54, 0x77, 0x6f, 0x12,
	0x21, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x69,
	0x74, 0x68, 0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f, 0x70, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e,
	0x74, 0x73, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22,
	0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x78, 0x12, 0x22, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x4f, 0x70, 0x41, 0x72,
	0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x1a, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x78, 0x22, 0x00, 0x12, 0x4f,
	0x0a, 0x07, 0x4c, 0x69, 0x73, 0x74, 0x53, 0x75, 0x6d, 0x12, 0x25, 0x2e, 0x63, 0x61, 0x6c, 0x63,
	0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x72, 0x69, 0x74, 0x68,
	0x6d, 0x65, 0x74, 0x69, 0x63, 0x4f, 0x70, 0x41, 0x72, 0x67, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x73,
	0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x42,
	0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x6d, 0x61, 0x69, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_dynamic_server_go_calculator_proto_rawDescOnce sync.Once
	file_dynamic_server_go_calculator_proto_rawDescData = file_dynamic_server_go_calculator_proto_rawDesc
)

func file_dynamic_server_go_calculator_proto_rawDescGZIP() []byte {
	file_dynamic_server_go_calculator_proto_rawDescOnce.Do(func() {
		file_dynamic_server_go_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamic_server_go_calculator_proto_rawDescData)
	})
	return file_dynamic_server_go_calculator_proto_rawDescData
}

var file_dynamic_server_go_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dynamic_server_go_calculator_proto_goTypes = []interface{}{
	(*ArithmeticOpArguments)(nil),     // 0: calculator.ArithmeticOpArguments
	(*SingleIntResult)(nil),           // 1: calculator.SingleIntResult
	(*ListArithmeticOpArguments)(nil), // 2: calculator.ListArithmeticOpArguments
	(*Complex)(nil),                   // 3: calculator.Complex
	(*ListComplexOpArguments)(nil),    // 4: calculator.ListComplexOpArguments
}
var file_dynamic_server_go_calculator_proto_depIdxs = []int32{
	3, // 0: calculator.ListComplexOpArguments.args:type_name -> calculator.Complex
	0, // 1: calculator.Calculator.AddTwo:input_type -> calculator.ArithmeticOpArguments
	0, // 2: calculator.Calculator.SubtractTwo:input_type -> calculator.ArithmeticOpArguments
	0, // 3: calculator.AdvancedCalculator.MultiplyTwo:input_type -> calculator.ArithmeticOpArguments
	4, // 4: calculator.AdvancedCalculator.ListSumComplex:input_type -> calculator.ListComplexOpArguments
	2, // 5: calculator.AdvancedCalculator.ListSum:input_type -> calculator.ListArithmeticOpArguments
	1, // 6: calculator.Calculator.AddTwo:output_type -> calculator.SingleIntResult
	1, // 7: calculator.Calculator.SubtractTwo:output_type -> calculator.SingleIntResult
	1, // 8: calculator.AdvancedCalculator.MultiplyTwo:output_type -> calculator.SingleIntResult
	3, // 9: calculator.AdvancedCalculator.ListSumComplex:output_type -> calculator.Complex
	1, // 10: calculator.AdvancedCalculator.ListSum:output_type -> calculator.SingleIntResult
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dynamic_server_go_calculator_proto_init() }
func file_dynamic_server_go_calculator_proto_init() {
	if File_dynamic_server_go_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamic_server_go_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArithmeticOpArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_server_go_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SingleIntResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_server_go_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListArithmeticOpArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_server_go_calculator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Complex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamic_server_go_calculator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListComplexOpArguments); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamic_server_go_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_dynamic_server_go_calculator_proto_goTypes,
		DependencyIndexes: file_dynamic_server_go_calculator_proto_depIdxs,
		MessageInfos:      file_dynamic_server_go_calculator_proto_msgTypes,
	}.Build()
	File_dynamic_server_go_calculator_proto = out.File
	file_dynamic_server_go_calculator_proto_rawDesc = nil
	file_dynamic_server_go_calculator_proto_goTypes = nil
	file_dynamic_server_go_calculator_proto_depIdxs = nil
}
