# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleAdd = channel.unary_unary(
                '/calculator.Calculator/SimpleAdd',
                request_serializer=calculator__pb2.ArithmeticOpArguments.SerializeToString,
                response_deserializer=calculator__pb2.SingleIntResult.FromString,
                )
        self.SimpleSubtract = channel.unary_unary(
                '/calculator.Calculator/SimpleSubtract',
                request_serializer=calculator__pb2.ArithmeticOpArguments.SerializeToString,
                response_deserializer=calculator__pb2.SingleIntResult.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimpleAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SimpleSubtract(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleAdd,
                    request_deserializer=calculator__pb2.ArithmeticOpArguments.FromString,
                    response_serializer=calculator__pb2.SingleIntResult.SerializeToString,
            ),
            'SimpleSubtract': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleSubtract,
                    request_deserializer=calculator__pb2.ArithmeticOpArguments.FromString,
                    response_serializer=calculator__pb2.SingleIntResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimpleAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/SimpleAdd',
            calculator__pb2.ArithmeticOpArguments.SerializeToString,
            calculator__pb2.SingleIntResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SimpleSubtract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/SimpleSubtract',
            calculator__pb2.ArithmeticOpArguments.SerializeToString,
            calculator__pb2.SingleIntResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AdvancedCalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ComplexOperation = channel.unary_unary(
                '/calculator.AdvancedCalculator/ComplexOperation',
                request_serializer=calculator__pb2.ComplexArithmeticOpArguments.SerializeToString,
                response_deserializer=calculator__pb2.ComplexArithmeticOpResult.FromString,
                )
        self.ListSum = channel.unary_unary(
                '/calculator.AdvancedCalculator/ListSum',
                request_serializer=calculator__pb2.ListArithmeticOpArguments.SerializeToString,
                response_deserializer=calculator__pb2.SingleIntResult.FromString,
                )


class AdvancedCalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ComplexOperation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdvancedCalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ComplexOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.ComplexOperation,
                    request_deserializer=calculator__pb2.ComplexArithmeticOpArguments.FromString,
                    response_serializer=calculator__pb2.ComplexArithmeticOpResult.SerializeToString,
            ),
            'ListSum': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSum,
                    request_deserializer=calculator__pb2.ListArithmeticOpArguments.FromString,
                    response_serializer=calculator__pb2.SingleIntResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.AdvancedCalculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdvancedCalculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ComplexOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.AdvancedCalculator/ComplexOperation',
            calculator__pb2.ComplexArithmeticOpArguments.SerializeToString,
            calculator__pb2.ComplexArithmeticOpResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListSum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.AdvancedCalculator/ListSum',
            calculator__pb2.ListArithmeticOpArguments.SerializeToString,
            calculator__pb2.SingleIntResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
